---

homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_directories:
  - bin
  - Caskroom
  - Cellar
  - etc
  - Frameworks
  - Homebrew
  - include
  - lib
  - opt
  - sbin
  - share
  - share/zsh
  - share/zsh/site-functions
  - var

homebrew_casks:
  - dropbox
  - firefox
  - font-fira-code
  - font-source-code-pro
  - google-chrome
  - hammerspoon
  - iterm2
  - slack
  - spotify
  - typora
  - visual-studio-code

homebrew_packages:
  - bat
  - croc
  - diff-so-fancy
  - dockutil
  - fzf
  - htop
  - imagemagick
  - jq
  - nvm
  - openssl
  - pyenv
  - shellcheck
  - the_silver_searcher
  - thefuck
  - tldr
  - wget
